language: python
python:
  - "2.7"

# command to install dependencies
install:
 - pip install -r requirements.txt
 - pip install coveralls

# command to execute test suite
script:
 - flake8 --max-line-length=100
 - nosetests --with-coverage

# Send results of tests to coveralls
after_success:
 - coveralls